### PR TITLE
baobab-chart: Fix tooltips not being displayed

### LINKED ISSUE #206: Disk Usage Analyzer hover-text behaviour
Cross posted from the Ubuntu MATE bug.launchpad (link at bottom of description)

I have been using Ubuntu GNOME 16.04.5 and Ubuntu MATE 18.04.1 on two different systems. I noticed different behaviour between GNOME Disk Usage Analyzer and MATE Disk Usage Analyzer, with the latter having less predictable behaviour with respect to the "tooltip" or "hovertext" (sorry I don't know the correct term) which appears when you are hovering over the ring chart.

When hovering over the grey circle in the centre, sometimes the current folder name and disk usage is displayed in a black label while the subordinate directory names are displayed as a grey label with a leader line to the ring representing that directory. Other times, nothing is displayed. Strangely, if you keep your mouse cursor slowly moving within a ring it will ensure that the grey labels appear. They will disappear immediately if the mouse stops moving. I am not certain what provokes the black labels to appear as this seems random to me. This was not the case with my experience on GNOME Disk Usage Analyzer and I suspect is contrary to what most users would want to happen.

I recommend that this be fixed so that the labels appear when the mouse hovers or moves over a ring.

#### Current Behaviour
Example of no labels appearing when hovering over a ring.
current

example with labels while moving mouse continuously. 
current2

#### Linux Distribution

Ubuntu MATE 18.04.1

#### Link to downstream report of your Distribution

[Ubuntu MATE bug entry](https://bugs.launchpad.net/ubuntu-mate/+bug/1785411)

### PR DESCRIPTION
**Pull request by lightdarkgreen**
Fixes #206

Sometimes (depending on the theme and window compositing settings) a leave event immediately followed by an enter event is triggered when a tooltip is first displayed.  The leave event was causing the highlighted item to stop being highlighted, and since the query-tooltip handler checks if any item is highlighted, this stopped the tooltip from being displayed.  The item would also not be highlighted again on the subsequent enter event, so the other labels on the chart would never appear.

This patch adds a handler for the enter event to properly highlight the item again, and maintains a pointer to the item which should have a tooltip displayed for it separately from the pointer to the currently highlighted item.

### CODE REVIEW

File: baobab/src/baobab-chart.c
Comment (vkareh) [inline baobab/src/baobab-chart.c:494]: You need to set `priv->tooltip_item = NULL;` here to avoid a dangling pointer...

File: baobab/src/baobab-chart.c [hunk 1]
```diff
@@ -997,9 +1001,10 @@ baobab_chart_set_item_highlight (GtkWidget *chart,
                               &item->rect, TRUE);
 }
 
-static gint
-baobab_chart_motion_notify (GtkWidget *widget,
-                            GdkEventMotion *event)
+static void
+baobab_chart_highlight_item_at_position (GtkWidget *widget,
+                                         gint x,
+                                         gint y)
```
Comment (vkareh) [inline baobab/src/baobab-chart.c]: These should be gdouble to avoid an implicit cast when calling `is_point_over_item`

File: baobab/src/baobab-chart.c [hunk 2]
```diff
@@ -1058,6 +1077,22 @@ baobab_chart_leave_notify (GtkWidget *widget,
...
+                           GdkEventCrossing *event)
+{
+  BaobabChartPrivate *priv;
+
+  /* Highlight any item the pointer is over */
+  baobab_chart_highlight_item_at_position (widget, event->x, event->y);
+
+  /* Set the tooltip item to the highlighted item, if any */
+  priv = BAOBAB_CHART (widget)->priv;
+  priv->tooltip_item = priv->highlighted_item;
```
Comment (vkareh) [inline baobab/src/baobab-chart.c]: Since you set `tooltip_item` on `enter-notify-event`, you should probably clear it in `leave-notify-event`

**Review by vkareh — CHANGES_REQUESTED** [review]

**Comment by lightdarkgreen** [comment]
While fixing the dangling pointer, I realized it's not really necessary to have `tooltip_item` and `highlight_item` be different, as long as `enter-notify-event` is handled; so I removed the `tooltip_item` variable completely.

**Review by vkareh — APPROVED** [review]
